owner: error-try-again
repo: QRGen-upptime

sites:
  - name: QRGen
    url: https://qr-gen.net
  - name: Void Subdomain
    url: https://void.qr-gen.net
  - name: QRGen Backend API
    url: https://void.qr-gen.net/qr/health

status-website:
  cname: status.qr-gen.net
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: QRGen Status & Outages
  introTitle: "Provides a canary for outages and upcoming maintenance, powered by Upptime."
  introMessage: This page uses **real-time** data pulled from [QRGen](https://qr-gen.net).
  navbar:
    - title: Status
      href: /
    - title: Github
      href: https://github.com/error-try-again/QRGen-upptime
